CREATE TABLE IF NOT EXISTS project
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS my_user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(100) NOT NULL,
    keyword varchar(255) NOT NULL,
    role varchar(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS subproject
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    project_id LONG NULL,
    foreign key(project_id) references project(id)
);

CREATE TABLE IF NOT EXISTS task
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) ,
    status VARCHAR(20) NOT NULL,
    creation_date DATE,
    update_date DATE,
    message text,
    my_user_id LONG NULL,
    foreign key(my_user_id) references my_user(id),
    subproject_id LONG NULL,
    foreign key(subproject_id) references subproject(id)
);

// Заполнение таблиц тестовыми данными
// !!! БД игнорирует первый INSERT пользователя в базу данных, поэтому пришлось повторять запрос
// Этот "баг" никак не решил, оставил так, все работает нормально
INSERT INTO my_user(username, keyword, role) values ('user', '{noop}password', 'ROLE_USER');
INSERT INTO my_user(username, keyword, role) values ('user', '{noop}password', 'ROLE_USER');
INSERT INTO my_user(username, keyword, role) values ('admin', '{noop}password', 'ROLE_ADMIN');

INSERT INTO project(title) values ( 'some IT job' );
INSERT INTO project(title) values ( 'some manager job' );

INSERT INTO subproject( title, project_id) VALUES (  'java-web', 1 );
INSERT INTO subproject( title, project_id) VALUES (  'php-web', 1 );
INSERT INTO subproject( title, project_id) VALUES (  'cpp-desktop', 1 );
INSERT INTO subproject( title, project_id) VALUES (  'management', 2 );

INSERT INTO task(type, status, creation_date, update_date, message, my_user_id, subproject_id)
VALUES ('FOR_DEVELOPER', 'NEW', '2023-12-08', '2023-12-10', 'do some stuff', 1, 1 );

INSERT INTO task(type, status, creation_date, update_date, message, my_user_id, subproject_id)
VALUES ('FOR_DEVELOPER', 'PROGRESS', '2023-11-08', '2023-12-18', 'do some stuff', 2, 4 );

INSERT INTO task(type, status, creation_date, update_date, message, my_user_id, subproject_id)
VALUES ('FOR_DEVELOPER', 'PROGRESS', '2022-02-08', '2023-12-08', 'do some stuff', 2, 2 );

INSERT INTO task(type, status, creation_date, update_date, message, my_user_id, subproject_id)
VALUES ('FOR_MANAGER', 'NEW', '2020-03-08', '2023-05-09', 'do some stuff', 2, 4 );

INSERT INTO task(type, status, creation_date, update_date, message, my_user_id, subproject_id)
VALUES ('FOR_MANAGER', 'DONE', '2022-12-08', '2023-12-12', 'do some stuff', 1, 3 );
